// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ToDo_API.Models;

public partial class TODOContext : DbContext
{
    public TODOContext(DbContextOptions<TODOContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ToDo> ToDos { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ToDo>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__ToDo__3213E83F36BB323C");

            entity.ToTable("ToDo");

            entity.Property(e => e.id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.description).IsRequired();
            entity.Property(e => e.lastUpdatedOn).HasColumnType("datetime");
            entity.Property(e => e.title)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.user).WithMany(p => p.ToDos)
                .HasForeignKey(d => d.userId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ToDo__userId__286302EC");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.userId).HasName("PK__Users__CB9A1CFF0C1636FA");

            entity.Property(e => e.userId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.dateOfBirth).HasColumnType("datetime");
            entity.Property(e => e.lastUpdatedOn).HasColumnType("datetime");
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.password)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.profilePic)
                .IsRequired()
                .HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}