// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDo_API.Models;

public partial class ToDo
{
    public Guid id { get; set; }

    public Guid userId { get; set; }

    public string title { get; set; }

    public DateTime lastUpdatedOn { get; set; }

    public string description { get; set; }

    public virtual User user { get; set; }
}