// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDo_API.Models;

public partial class User
{
    public Guid userId { get; set; }

    public string name { get; set; }

    public DateTime dateOfBirth { get; set; }

    public string profilePic { get; set; }

    public DateTime lastUpdatedOn { get; set; }

    public string password { get; set; }

    public virtual ICollection<ToDo> ToDos { get; set; } = new List<ToDo>();
}